//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekiroTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SekiroTool.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string AddExperience {
            get {
                return ResourceManager.GetString("AddExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///41 b8 01 00 00 00       mov    r8d,0x1
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string AddSen {
            get {
                return ResourceManager.GetString("AddSen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 e0                mov    rax,rsp
        ///55                      push   rbp
        ///56                      push   rsi
        ///50                      push   rax
        ///48 8b 01                mov    rax,QWORD PTR [rcx]
        ///81 78 18 21 ac 08 03    cmp    DWORD PTR [rax+0x18],0x308ac21
        ///75 0e                   jne    20 &lt;exit&gt;
        ///0f 2f 1d 00 00 00 00    comiss xmm3,DWORD PTR [rip+0x0]        # 19 &lt;_main+0x19&gt;
        ///75 05                   jne    20 &lt;exit&gt;
        ///ba ff ff ff ff          mov    edx,0xffffffff
        ///000000000020 &lt;exit&gt;:
        ///58             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ButterflyNoSnap {
            get {
                return ResourceManager.GetString("ButterflyNoSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba ba 00 03 10 00    movabs rdx,0x100300ba
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///48 85 c0                test   rax,rax
        ///74 29                   je     56 &lt;exit&gt;
        ///48 8b 00                mov    rax,QWORD PTR [rax]
        ///48 89 c3                mov    rbx,rax
        ///48 8b 40 58             mov    rax,QWORD PTR [rax+0x58]
        ///48 83  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DragonSkipPhaseOne {
            get {
                return ResourceManager.GetString("DragonSkipPhaseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 8b 80 f8 1f 00 00    mov    rax,QWORD PTR [rax+0x1ff8]
        ///48 3b 48 18             cmp    rcx,QWORD PTR [rax+0x18]
        ///58                      pop    rax
        ///0f 84 00 00 00 00       je     1a &lt;_main+0x1a&gt;
        ///48 89 5c 24 30          mov    QWORD PTR [rsp+0x30],rbx
        ///e9 00 00 00 00          jmp    24 &lt;_main+0x24&gt;.
        /// </summary>
        internal static string FreezeTargetPosture {
            get {
                return ResourceManager.GetString("FreezeTargetPosture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///88 01                   mov    BYTE PTR [rcx],al
        ///c3                      ret.
        /// </summary>
        internal static string GetEvent {
            get {
                return ResourceManager.GetString("GetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 38             sub    rsp,0x38
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # b &lt;_main+0xb&gt;
        ///48 8d 15 00 00 00 00    lea    rdx,[rip+0x0]        # 12 &lt;_main+0x12&gt;
        ///4d 31 c0                xor    r8,r8
        ///4d 31 c9                xor    r9,r9
        ///44 89 44 24 24          mov    DWORD PTR [rsp+0x24],r8d
        ///44 89 44 24 28          mov    DWORD PTR [rsp+0x28],r8d
        ///e8 00 00 00 00          call   27 &lt;_main+0x27&gt;
        ///48 83 c4 38             add    rsp,0x38
        ///c3                      ret.
        /// </summary>
        internal static string GiveItem {
            get {
                return ResourceManager.GetString("GiveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 8b 80 88 00 00 00    mov    rax,QWORD PTR [rax+0x88]
        ///48 3b 46 08             cmp    rax,QWORD PTR [rsi+0x8]
        ///58                      pop    rax
        ///0f 84 00 00 00 00       je     1a &lt;_main+0x1a&gt;
        ///4c 89 bc 24 a0 00 00    mov    QWORD PTR [rsp+0xa0],r15
        ///00
        ///e9 00 00 00 00          jmp    27 &lt;_main+0x27&gt;.
        /// </summary>
        internal static string InfinitePoise {
            get {
                return ResourceManager.GetString("InfinitePoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 05 00 00 00 00    mov    QWORD PTR [rip+0x0],rax        # 7 &lt;_main+0x7&gt;
        ///48 8b 80 f8 1f 00 00    mov    rax,QWORD PTR [rax+0x1ff8]
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string LockedTarget {
            get {
                return ResourceManager.GetString("LockedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f3 0f 58 86 00 09 00    addss  xmm0,DWORD PTR [rsi+0x900]
        ///00
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 10 &lt;_main+0x10&gt;
        ///48 8b 80 88 00 00 00    mov    rax,QWORD PTR [rax+0x88]
        ///48 3b 46 08             cmp    rax,QWORD PTR [rsi+0x8]
        ///75 03                   jne    20 &lt;exit&gt;
        ///0f 57 c0                xorps  xmm0,xmm0
        ///000000000020 &lt;exit&gt;:
        ///58                      pop    rax
        ///e9 00 00 00 00          jmp    26 &lt;exit+0x6&gt;.
        /// </summary>
        internal static string NoClip_InAirTimer {
            get {
                return ResourceManager.GetString("NoClip_InAirTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ff 90 f8 00 00 00       call   QWORD PTR [rax+0xf8]
        ///84 c0                   test   al,al
        ///74 22                   je     2c &lt;exit&gt;
        ///49 83 fc 62             cmp    r12,0x62
        ///74 08                   je     18 &lt;set_down&gt;
        ///49 83 fc 7e             cmp    r12,0x7e
        ///74 0d                   je     23 &lt;set_up&gt;
        ///eb 14                   jmp    2c &lt;exit&gt;
        ///000000000018 &lt;set_down&gt;:
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # 1f &lt;set_down+0x7&gt;
        ///30 c0                   xor    al,al
        ///eb 09               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Keyboard {
            get {
                return ResourceManager.GetString("NoClip_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 83 f9 0b             cmp    r9d,0xb
        ///74 10                   je     16 &lt;set_down&gt;
        ///41 83 f9 0c             cmp    r9d,0xc
        ///74 12                   je     1e &lt;set_up&gt;
        ///49 89 e3                mov    r11,rsp
        ///53                      push   rbx
        ///56                      push   rsi
        ///e9 00 00 00 00          jmp    16 &lt;set_down&gt;
        ///000000000016 &lt;set_down&gt;:
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # 1d &lt;set_down+0x7&gt;
        ///c3                      ret
        ///00000000001e &lt;set_up&gt;:
        ///c6 05 00 00 00 00 02    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Triggers {
            get {
                return ResourceManager.GetString("NoClip_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 48             sub    rsp,0x48
        ///48 8d 0c 24             lea    rcx,[rsp]
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 48             add    rsp,0x48
        ///c3                      ret.
        /// </summary>
        internal static string OpenMenuNoParams {
            get {
                return ResourceManager.GetString("OpenMenuNoParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 48             sub    rsp,0x48
        ///48 8d 0c 24             lea    rcx,[rsp]
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///49 b9 00 00 00 00 00    movabs r9,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 48             add    rsp,0x48
        ///c3                      ret.
        /// </summary>
        internal static string OpenMenuThreeParams {
            get {
                return ResourceManager.GetString("OpenMenuThreeParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 48             sub    rsp,0x48
        ///48 8d 0c 24             lea    rcx,[rsp]
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 48             add    rsp,0x48
        ///c3                      ret.
        /// </summary>
        internal static string OpenMenuTwoParams {
            get {
                return ResourceManager.GetString("OpenMenuTwoParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///ba 0a 00 00 00          mov    edx,0xa
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///4d 31 c9                xor    r9,r9
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string SetEvent {
            get {
                return ResourceManager.GetString("SetEvent", resourceCulture);
            }
        }
    }
}
