using System.ComponentModel;

namespace SekiroTool.Enums;

public enum HotkeyActions
{
    SavePos1,
    SavePos2,
    RestorePos1,
    RestorePos2,
    SetMaxHp,
    NoDeath,
    NoDeathExKillbox,
    NoDamage,
    OneShotHealth,
    OneShotPosture,
    NoGoodsConsume,
    NoEmblemConsume,
    InfiniteRevival,
    PlayerHide,
    PlayerSilent,
    InfinitePoise,
    ApplyConfetti,
    ApplyGachiin,
    RemoveConfetti,
    RemoveGachiin,
    
    TogglePlayerSpeed,
    IncreasePlayerSpeed,
    DecreasePlayerSpeed,
    
    SkipDragonPhaseOne,
    TriggerDragonFinalAttack,
    NoButterflySummons,
    AllNoDeath,
    AllNoDamage,
    AllNoHit,
    AllNoAttack,
    AllNoMove,
    AllDisableAi,
    AllNoPostureBuildup,
    AllTargetingView,
    
    EnableTargetOptions,
    FreezeTargetHp,
    SetTargetOneHp,
    TargetCustomHp,
    FreezeTargetPosture,
    SetTargetOnePosture,
    TargetCustomPosture,
    ShowAllResistances,
    RepeatAct,
    RepeatKengekiAct,
    IncreaseTargetSpeed,
    DecreaseTargetSpeed,
    ToggleTargetSpeed,
    FreezeTargetAi,
    NoAttackTargetAi,
    NoMoveTargetAi,
    TargetNoPostureBuildup,
    TargetNoDeath,
    TargetTargetingView,
    Quitout,
    
    ToggleGameSpeed,
    IncreaseGameSpeed,
    DecreaseGameSpeed,
    NoClip,
    IncreaseNoClipSpeed,
    DecreaseNoClipSpeed,
    FreeCam,
    MoveCamToPlayer,
    
    
}